play.http.secret.key="a477be6f719deb7801c2a45f3715f146244d30ea1585a7a91e26822f3f2b905c"

db.janusgraph {
  storage.backend = cql
  storage.hostname = ["thehive-cassandra"]
  storage.cql.keyspace = thehive
  storage.cql.read-consistency-level = ONE
  storage.cql.write-consistency-level = ONE
}

storage {
  provider = s3
  s3 {
    bucket = "thehive"
    endpoint = "http://thehive-minio:9000"
    accessKey = "admin"
    secretKey = "adminadmin"
    region = "us-east-1"
    pathStyleAccess = true
  }
}

search {
  index = thehive
}

notification.webhook.endpoints = [
  {
    name: "shuffle"
    url: "http://shuffle-backend:5001/api/v1/hooks/a15dc028-1897-40a3-af76-9ce8290c9d15"
    version: 1
    wsConfig: {}
  }
]

