server {
    listen 55001;

    location / {
        proxy_pass https://single-node-wazuh.manager-1:55000;
        proxy_ssl_verify off;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto http;
    }
}

server {
    listen 9201;

    location / {
        proxy_pass https://single-node-wazuh.indexer-1:9200;
        proxy_ssl_verify off;

        proxy_set_header Host $host;
        proxy_set_header Authorization "Basic YWRtaW46U2VjcmV0UGFzc3dvcmQ=";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto http;
    }
}
